### ISSUE TITLE
TVNZ: No sources

### ISSUE THREAD

**Issue by JaxonPlays** [billybanana80/ozivine#2]
Hi there,

I'm having issues downloading TVNZ.

`Enter the video URL: https://www.tvnz.co.nz/shows/taskmaster-nz/episodes/s4-e10
Ozivine..........initiating TVNZ
Login successful, token obtained
No 'sources' found in the response`

**Comment by billybanana80** [comment]
The service can be a bit hit and miss with VPN's etc. Assuming you have a NZ IP and can play a video in the browser there is a potential solution.

go to line 43 of tvnz.py

replace
BRIGHTCOVE_API = lambda video_id: f"https://edge.api.brightcove.com/playback/v1/accounts/{BRIGHTCOVE_ACCOUNT}/videos/{video_id}"
with
BRIGHTCOVE_API = lambda video_id: f"https://playback.brightcovecdn.com/playback/v1/accounts/{BRIGHTCOVE_ACCOUNT}/videos/{video_id}"

does that resolve the issue ?

**Comment by JaxonPlays** [comment]
Working, cheers!

**Comment by billybanana80** [comment]
Master updated now.
