### ISSUE TITLE
9Now 1080p

### ISSUE THREAD

**Issue by JaxonPlays** [billybanana80/ozivine#3]
Hi there,

When downloading an episode from 9Now in 1080p. The filename is 720p.

**Comment by billybanana80** [comment]
Is that an Olympics video ?

**Comment by JaxonPlays** [comment]
Yes.

**Comment by billybanana80** [comment]
Which one ? What's the url

**Comment by JaxonPlays** [comment]
Any of the listed episodes: https://www.9now.com.au/breaking-olympic-games-paris-2024

**Comment by billybanana80** [comment]
I can't replicate that. The files download and are named 1080p from those I have tested from that link.

`LOG 2024/08/12
Save Path: D:\Downloads\bin\Logs
Task Start: 2024/08/12 07:28:30
Task CommandLine: N_m3u8DL-RE http://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/4460760524001/22bb1b3e-33da-4243-847d-fac216495307/2s/manifest.mpd?fastly_token=NjZiYWE1NDRfZWNhZTA3M2M2MjI5NzkzMjg2MDdmMxxxxxxxYjI2NjAyNWUxMDBjYmE3OWY0NTQ5Y2ZlNjZiOWYwNWUwNDI3Mw%3D%3D --select-video best --select-audio best --select-subtitle all -mt -M format=mkv --save-dir D:/Downloads/ --save-name Breaking.Olympic.Games.Paris.2024.S2024E06.1080p.9NOW.WEB-DL.AAC2.0.H.264 --key 8acd456fea2xxxxaaf4587ff3f85402:19c1ccc72cfe545ff354xxxxf0f289c8`

**Comment by JaxonPlays** [comment]
Ah that’s odd then.

**Comment by WeakTopology** [comment]
FWIW I seem to have this issue with 9Now and the following link: https://www.9now.com.au/lego-masters/season-7/episode-1

The files downloads as 720p with the following name: `Lego.Masters.S07E01.720p.9NOW.WEB-DL.AAC2.0.H.264.mkv`

EDIT: Actually, perhaps that is all that is available.

```
22:58:36.246 INFO : Extracted, there are 9 streams, with 5 basic streams, 3 audio streams, 1 subtitle streams
22:58:36.247 INFO : Vid *CENC 1280x720 | 1846 Kbps | 39d6b431-29b5-42af-a9fe-4baec73c03e5 | 25 | avc1.42001f | 1681 Segments | Main | 
~56m02s
22:58:36.248 INFO : Vid *CENC 1024x576 | 1135 Kbps | 8d6f26e0-908e-4d20-94f5-77a09a01ef19 | 25 | avc1.42001f | 1681 Segments | Main | 
~56m02s
22:58:36.249 INFO : Vid *CENC 768x432 | 596 Kbps | ed505cdb-d3ff-4064-b005-5e58fe9bbabe | 25 | avc1.4d001e | 1681 Segments | Main | ~56m02s
22:58:36.249 INFO : Vid *CENC 640x360 | 411 Kbps | 530c0880-c5d0-4fb2-aa8f-0e48bb116cfe | 25 | avc1.4d001e | 1681 Segments | Main | ~56m02s
22:58:36.250 INFO : Vid *CENC 480x270 | 249 Kbps | d7f496c0-c0e1-4967-a975-cb2c47c8b989 | 25 | avc1.420015 | 1681 Segments | Main | ~56m02s
22:58:36.251 INFO : Aud *CENC 1ee445e9-9708-4f28-9121-f4fccc90cf0a | 127 Kbps | mp4a.40.2 | en | 1684 Segments | Main | ~56m02s
22:58:36.252 INFO : Aud *CENC 7d1087e1-052b-45dc-b194-964e291f8005 | 96 Kbps | mp4a.40.2 | en | 1684 Segments | Main | ~56m02s
22:58:36.252 INFO : Aud *CENC 43ccd033-9e12-456a-a74e-891283327295 | 64 Kbps | mp4a.40.2 | en | 1684 Segments | Main | ~56m02s
22:58:36.253 INFO : Sub 23525d4d-ed5e-4f42-bef7-9fbdd854f63f | en | 1 Segment | ~56m01s
22:58:36.253 INFO : Parsing streams...
22:58:36.301 INFO : Selected streams:
22:58:36.302 INFO : Vid *CENC 1280x720 | 1846 Kbps | 39d6b431-29b5-42af-a9fe-4baec73c03e5 | 25 | avc1.42001f | 1681 Segments | Main | 
```

I was just a bit surprised that there was no 1080p option!
