### ISSUE TITLE
Support 7plus Season & Episode Numbers

### ISSUE THREAD

**Issue by JaxonPlays** [billybanana80/ozivine#4]
Could use regex to grab the numbers.

Example -

Link: https://7plus.com.au/below-deck-down-under?episode-id=4NBCU2330-S2T18
-->
ID: 4NBCU2330-S2T18
-->
S2T18
-->
S02E18

However, if you browse the site there are other variations.

eg. The Front Bar = FBAR24-026

**Comment by billybanana80** [comment]
I'm not sure your question. I've already catered for the diferent naming conventions.

Both https://7plus.com.au/the-front-bar?episode-id=FBAR24-026 and https://7plus.com.au/below-deck-down-under?episode-id=4NBCU2330-S2T18 download fine.

**Comment by JaxonPlays** [comment]
Ah it seems that they delay adding season and episode numbers after they just add them.

Here's an example of a show that does not support season and episode numbers:

https://7plus.com.au/seven-news-adelaide?episode-id=7NNA24-219&autoplay=true

**Comment by billybanana80** [comment]
That episode has dropped off the site now. I was able to get all of the https://7plus.com.au/seven-news-adelaide?episode-id=7NNA24-226 to https://7plus.com.au/seven-news-adelaide?episode-id=7NNA24-221 that do exist without any issue.

**Comment by JaxonPlays** [comment]
When downloading they all have the same filename.
